### ISSUE TITLE
zoom very touchy with touchpad two-finger zoom (Mac)

### ISSUE THREAD

**Issue by knownasilya** [jQueryGeo/geo#152]
Basically the zoom either goes full in or full out. It's just too sensitive to the touch pad for some reason. This does not happen with Leaflet or GMaps, so it's not a sensitivity issue.

Tested on late-2013 MBP with OSX 10.9.1 using Google Chrome 32.0.1700.107.

**Comment by ryanttb** [comment]
If possible, can you test if this is still an issue with our new 1.0.0-b2 release? Thanks!

http://jquerygeo.com/

http://code.jquerygeo.com/jquery.geo-1.0.0-b2.min.js

**Comment by knownasilya** [comment]
Still the same, I tested it with the utah demo on the site.

**Comment by ryanttb** [comment]
Ok, thank you for testing!
